name: clang-format lint

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: daniestevez/clang-format-lint-action@master
      with:
        source: '.'
        extensions: 'h,hpp,cpp,cc'
